baseURL = "https://somarosa.co.uk"
title = "Somarosa"
author = "Anya Walsh"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = [] # ['blog']

  googleFonts = false

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Anya Walsh"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Anya Walsh"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Anya Walsh -  Temple Priestess, Sacred Sexuality, Somatic Embodiment & Women's work facilitator, Vocal Star Reiki Healer, Yoga Teacher, Ceremonial Dancer, Ceremonial Vocalist and Artist"
    meta_og_title = "Somarosa"
    meta_og_type = "website"
    meta_og_url = "https://somarosa.co.uk"
    meta_og_image = "https://somarosa.co.uk/img/link-preview.png" # TODO
    meta_og_description = "Anya Walsh -  Temple Priestess, Sacred Sexuality, Somatic Embodiment & Women's work facilitator, Vocal Star Reiki Healer, Yoga Teacher, Ceremonial Dancer, Ceremonial Vocalist and Artist."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username" # TODO
    meta_twitter_creator = "@username" # TODO

[menu]

  # -------- Parent: 1-1 Sanctuary --------
  [[menu.main]]
    identifier = "1-1-sanctuary"
    name = "1-1 Sanctuary"
    url = "/sanctuary/"
    weight = 1

  [[menu.main]]
    name = "Revitalise Your Life Sanctuary"
    url = "/sanctuary/revitalise-your-life-sanctuary/"
    parent = "1-1-sanctuary"
    weight = 11

  [[menu.main]]
    name = "Tantric Bodywork"
    url = "/sanctuary/tantric-bodywork/"
    parent = "1-1-sanctuary"
    weight = 12

  [[menu.main]]
    name = "Sanctuary Programs"
    url = "/sanctuary/sanctuary-programs/"
    parent = "1-1-sanctuary"
    weight = 22


  # -------- Parent: Workshops --------
  [[menu.main]]
    identifier = "workshops"
    name = "Workshops"
    url = "/workshops/"
    weight = 2

  [[menu.main]]
    name = "The Rose Temple"
    url = "/workshops/rose-temple/"
    parent = "workshops"
    weight = 20

  [[menu.main]]
    name = "Online Workshops"
    url = "/workshops/online-workshops/"
    parent = "workshops"
    weight = 21

  [[menu.main]]
    name = "Women's Temple"
    url = "/workshops/womens-temple/"
    parent = "workshops"
    weight = 22

# -------- Other top-level items -------- 
[[menu.main]] 
name = "About" 
url = "/about/" 
weight = 30 

[[menu.main]] 
name = "Contact" 
url = "/contact/" 
weight = 40

  # ----------- Footer Menu -----------

  [[menu.footer]]
    name = "Home"
    url = "/"
    pre = '<i class="fa-solid fa-house"></i>'
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/niccokunzmann/somarosa.co.uk"
    pre = "<i class='fa-brands fa-github'></i>"
#    pre = "<img class='text-2xl' src='https://img.shields.io/github/actions/workflow/status/niccokunzmann/somarosa.co.uk/hugo.yml?branch=main&style=flat&logo=github'/>"
      weight = 10

  [[menu.footer]]
    name = "Instagram"
    url = "https://www.instagram.com/somarosa.uk/"
    pre = "<i class='fa-brands fa-instagram'></i>"
      weight = 2

  [[menu.footer]]
    name = "Facebook"
    url = "https://www.facebook.com/somarosaonline/"
    pre = "<i class='icon-facebook text-2xl'></i>"
      weight = 3

  [[menu.footer]]
    name = "Email"
    url = "mailto:somarosauk@gmail.com"
    pre = "<i class='icon-email text-2xl'></i>"
      weight = 4

